### ISSUE TITLE
Experiment with serde annotation suggestion in prost_serde FAQ

### ISSUE THREAD

**Issue by brainstorm** [umccr/BioSerDe#2]
Take the hint from [prost_serde](https://github.com/tokio-rs/prost#faq)'s FAQ and iterate so that we have straightforward SerDe for BED:

> (...)But it is possible to place serde derive tags onto the generated types, so the same structure can support both prost and Serde.

Next step: Level up with another format such as VCF.

**Comment by GabrielSimonetto** [comment]
Made an initial exploration of this is the [issue-2 branch](https://github.com/umccr/BioSerDe/compare/master...issue-2).

It requires only a few modifications to be able to serialize proto generated files. I've tried to make intelligible steps between each commits in order to make the process easy to follow, but mostly [just deriving](https://github.com/umccr/BioSerDe/commit/4126fd89bc7477d803e47a1eb3d90b2d6c32d062) `Serialize` and `Deserialize` from serde solves the problem. I don't fully understand the points that the FAQ raises (and, it is 5 years old, so there is a chance that the scenario has changed), but it seems like we can try to keep iterating on this format.

I have a few questions as to how to move forward (and which of these plans should be tried first)

1) About trying to do the same with VCF: I've noted that we don't yet have a `vcf.proto` file, so should I build it from scratch? That sounds like something that I would need to do at some point anyhow, but I wanted to confirm that this is the plan.

2) Also, we talked briefly about how we would need to drop the fully automated `build.rs` usage of proto files, since from now on it would need human intervention to make the format usable. [As used in the ica-rs repo](https://github.com/umccr-illumina/ica-rs/blob/master/gds/.openapi-generator-ignore), I couldn't figure out what would be the internal workings of stopping the build process for the ignored files, is it fair to assume that that would be coded by us in the build script, or is there some crate that is able derive this functionality using the .ignored files?

**Comment by multimeric** [comment]
1. Yes, if there is no proto file for VCF then write the struct yourself. Perhaps have a look at the generated Rust code for inspiration (or not, if it doesn't help), which brings us to...
2. Yes, I think we should drop the automated building. Are you asking how to prevent certain subsets from being re-built using an ignore file? I think it would be easier to just tweak the `build.rs` here, and to remove the path that captures all the proto files, and instead just list out the ones you want to be generated: https://github.com/umccr/BioSerDe/blob/584cc72034e5d3b17ce78771042719b82d2ebb25/build.rs#L6

**Comment by GabrielSimonetto** [comment]
@multimeric actually I was thinking about building a VCF proto file instead of directly writing a rust file, just to keep things normalized. But it seems like maybe we are just dropping proto files altogether, right? Would we be losing some important functionality/flexibility if we just start using regular rust files from now on?

**Comment by brainstorm** [comment]
Hey, yes, I concur with Michael. The protobuf idea was more of a stepping
stone/poc, if that stays too much in the way for our goals, lets change it!
